// chaotix_recomp: static recompiler for Knuckles' Chaotix (68000 + 2x SH-2).
//
//   chaotix_recomp --rom <file> [--coverage f.cov ...] --out <generated dir>
//
// Output (derived from the user's ROM, never committed):
//   recomp_decls.h, recomp_tables.cpp, recomp_m68k_NNN.cpp, recomp_sh2_NNN.cpp,
//   sources.cmake, manifest.txt
#include "emit.h"
#include "runtime/rom.h"
#include <algorithm>
#include <cstdio>
#include <filesystem>

using namespace chaotix;
using namespace chaotix::analysis;
using namespace chaotix::recompiler;

static bool write_file(const std::string& path, const std::string& s) {
    FILE* f = std::fopen(path.c_str(), "w");
    if (!f) return false;
    std::fwrite(s.data(), 1, s.size(), f);
    std::fclose(f);
    return true;
}

int main(int argc, char** argv) {
    std::string rom_path, out_dir;
    std::vector<std::string> cov_paths;
    EmitOptions opt;
    bool heuristics = true;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--rom" && i + 1 < argc) rom_path = argv[++i];
        else if (a == "--coverage" && i + 1 < argc) cov_paths.push_back(argv[++i]);
        else if (a == "--out" && i + 1 < argc) out_dir = argv[++i];
        else if (a == "--no-heuristics") heuristics = false;
        else { std::fprintf(stderr, "unknown argument %s\n", a.c_str()); return 2; }
    }
    if (rom_path.empty() || out_dir.empty()) {
        std::fprintf(stderr, "usage: chaotix_recomp --rom <file> [--coverage f.cov ...] --out <dir>\n");
        return 2;
    }
    Rom rom;
    std::string err;
    if (!rom.load(rom_path, &err)) { std::fprintf(stderr, "error: %s\n", err.c_str()); return 1; }
    if (rom.version == RomVersion::Unknown) {
        std::fprintf(stderr, "error: ROM not recognised (sha1 %s). Only the verified Knuckles' Chaotix image is supported.\n", rom.sha1.c_str());
        return 1;
    }
    std::vector<CoverageEntry> cov;
    for (const auto& c : cov_paths) {
        auto v = load_coverage(c, &err);
        if (v.empty()) std::fprintf(stderr, "warning: %s: no coverage entries (%s)\n", c.c_str(), err.c_str());
        cov.insert(cov.end(), v.begin(), v.end());
    }
    std::filesystem::create_directories(out_dir);
    // Remove stale generated sources.
    for (const auto& e : std::filesystem::directory_iterator(out_dir)) {
        std::string n = e.path().filename().string();
        if (n.rfind("recomp_", 0) == 0) std::filesystem::remove(e.path());
    }
    opt.out_dir = out_dir;

    Program pm(rom, Cpu::M68K), ps(rom, Cpu::SH2);
    for (Program* p : {&pm, &ps}) {
        p->add_default_spaces();
        p->heuristics = heuristics;
        p->add_coverage(cov);
        p->analyze();
    }
    EmitResult rm, rs;
    emit_m68k(pm, opt, rm);
    emit_sh2(ps, opt, rs);

    // Declarations header
    std::string decls = "// Generated by chaotix_recomp. Do not edit; do not commit.\n#pragma once\n#include \"game/recomp_api.h\"\n\nnamespace recomp {\n";
    for (const auto& d : rm.decls) decls += d + "\n";
    for (const auto& d : rs.decls) decls += d + "\n";
    decls += "} // namespace recomp\n";
    write_file(out_dir + "/recomp_decls.h", decls);

    // Tables
    std::sort(rm.table.begin(), rm.table.end(), [](const TableEntry& a, const TableEntry& b) { return a.key < b.key; });
    std::sort(rs.table.begin(), rs.table.end(), [](const TableEntry& a, const TableEntry& b) { return a.key < b.key; });
    std::string t = "// Generated by chaotix_recomp. Do not edit; do not commit.\n#include \"recomp_decls.h\"\n\nnamespace recomp {\n\n";
    t += "const char g_rom_sha1[] = \"" + rom.sha1 + "\";\n\n";
    t += "const M68kEntry g_m68k_entries[] = {\n";
    char buf[256];
    for (const auto& e : rm.table) { std::snprintf(buf, sizeof buf, "  {0x%08Xu, %s},\n", e.key, e.fn.c_str()); t += buf; }
    t += "};\nconst size_t g_m68k_entry_count = sizeof(g_m68k_entries) / sizeof(g_m68k_entries[0]);\n\n";
    t += "const Sh2Entry g_sh2_entries[] = {\n";
    for (const auto& e : rs.table) {
        std::snprintf(buf, sizeof buf, "  {0x%08Xu, %s, %u, %u},\n", e.key, e.fn.c_str(), e.range_begin, e.range_count);
        t += buf;
    }
    t += "};\nconst size_t g_sh2_entry_count = sizeof(g_sh2_entries) / sizeof(g_sh2_entries[0]);\n\n";
    t += "const CodeRange g_sh2_ranges[] = {\n";
    for (const auto& r : rs.ranges) { std::snprintf(buf, sizeof buf, "  {0x%08Xu, %u, 0x%06Xu},\n", r[0], r[1], r[2]); t += buf; }
    if (rs.ranges.empty()) t += "  {0, 0, 0},\n";
    t += "};\nconst size_t g_sh2_range_count = " + std::to_string(rs.ranges.size()) + ";\n\n} // namespace recomp\n";
    write_file(out_dir + "/recomp_tables.cpp", t);

    // CMake source list
    std::string cm = "# Generated by chaotix_recomp\nset(CHAOTIX_GENERATED_SOURCES\n";
    for (const auto& f : rm.files) cm += "    ${CHAOTIX_GENERATED_DIR}/" + f + "\n";
    for (const auto& f : rs.files) cm += "    ${CHAOTIX_GENERATED_DIR}/" + f + "\n";
    cm += "    ${CHAOTIX_GENERATED_DIR}/recomp_tables.cpp\n)\n";
    write_file(out_dir + "/sources.cmake", cm);

    std::string man;
    std::snprintf(buf, sizeof buf, "rom_sha1 %s\nm68k functions %zu instructions %zu entries %zu\nsh2 functions %zu instructions %zu entries %zu folded_literals %zu validation_ranges %zu\ncoverage_entries %zu\n",
                  rom.sha1.c_str(), rm.functions, rm.instructions, rm.table.size(), rs.functions, rs.instructions, rs.table.size(),
                  rs.folded_literals, rs.ranges.size(), cov.size());
    man = buf;
    std::snprintf(buf, sizeof buf, "m68k_static_recovery branch_tables %zu offset_tables %zu code_pointers %zu\n",
                  pm.stats.branch_tables, pm.stats.offset_tables, pm.stats.code_pointers);
    man += buf;
    man += "sh2_fast_forward_loops " + std::to_string(rs.fast_loops) + std::string(1, 10);
    write_file(out_dir + "/manifest.txt", man);
    std::printf("%s", man.c_str());
    for (const auto& w : ps.warnings) std::printf("warning (sh2): %s\n", w.c_str());
    return 0;
}
