// SDL3 platform layer: window, rendering, input, timing, storage paths.
//
// This is the only file that talks to SDL. Game/runtime code sees only
// InputState, the output framebuffer and SaveStore paths. SDL_Renderer picks a
// native backend per platform (Direct3D 11/12, Metal, Vulkan, OpenGL/ES), so
// no graphics API is referenced directly.
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

#include "frontend/config.h"
#include "frontend/time_attack.h"
#include "frontend/debug_overlay.h"
#include "frontend/setup.h"
#include "platform/sdl_setup.h"
#include "platform/menu.h"
#include "platform/ui.h"
#include "game/achievements.h"
#include "game/recomp_dispatch.h"
#include "input/input.h"
#include "input/touch_controls.h"
#include "renderer/image_io.h"
#include "renderer/viewport.h"
#include "runtime/log.h"
#include "runtime/patches.h"
#include "runtime/save.h"
#include "runtime/system.h"

#include <algorithm>
#include <chrono>
#include <map>
#include <cmath>
#include <cstdio>
#include <filesystem>
#include <memory>
#include <string>
#include <vector>

using namespace chaotix;

namespace chaotix {
// Generated by cmake/embed_file.cmake from assets/achievements.ini, so the
// shipped definitions are always present (an APK has nowhere to put them).
extern const unsigned char achievements_ini[];
extern const size_t achievements_ini_len;
} // namespace chaotix

namespace {

// Far enough that a touch is never mistaken for a tap.
constexpr float kNotATap = 1e9f;

// Original NTSC field rate: 53.693175 MHz / (3420 * 262).
constexpr double kNtscFrameRate = 53693175.0 / (3420.0 * 262.0);

struct App {
    Config cfg;
    SaveStore store;
    std::unique_ptr<Machine> m;
    SDL_Window* window = nullptr;
    SDL_Renderer* renderer = nullptr;
    SDL_Texture* texture = nullptr;
    SDL_AudioStream* audio = nullptr;
    std::vector<SDL_Gamepad*> pads;
    TouchControls touch;
    bool touch_enabled = false;
    std::map<SDL_FingerID, uint16_t> fingers;
    bool running = true;
    bool fast_forward = false;
    int overlay_page = 0;
    FrameTiming timing;
    std::vector<uint32_t> watches = {0xFFF000, 0xFFF010};
    uint64_t sram_dirty_since = 0;
    // --autotest: run N frames with scripted input, capture the presented
    // image (what the user would see) and exit. Used by rendering tests.
    uint64_t autotest_frames = 0;
    std::string autotest_shot;
    struct Press { uint64_t frame, duration; uint16_t buttons; };
    std::vector<Press> script;
    // --hold: the same thing but fed into the host's own input path, so it
    // passes through the menu and the Start interception the way a real
    // button does. --press goes straight to the emulated pad instead.
    struct Hold { uint64_t frame; uint16_t buttons; int remaining = 0; bool armed = false; };
    std::vector<Hold> host_script;
    // --keys: synthetic key presses at given frames, pushed as real SDL
    // events so they travel the same path a keyboard does. For testing the
    // menu flows, which scripted pad input cannot reach.
    struct KeyAt { uint64_t frame; SDL_Keycode key; bool done = false; };
    std::vector<KeyAt> key_script;
    // --shots: extra captures, so one run can show a whole flow.
    struct Shot { uint64_t frame; std::string path; bool done = false; };
    std::vector<Shot> extra_shots;
    // Achievements: evaluated once per emulated frame, unlocks shown as a
    // notification and written to the save folder straight away.
    achievements::Tracker achievements;
    ui::Ui ui;
    bool achievements_on = false;
    Menu menu;
    int inject_start = 0;   // frames of Start to hand the game on the way out
    // A stage the front end asked for is taken at the game's mode dispatcher,
    // which the title screen only reaches once it is done with itself: one
    // press of Start gets past its animation, another leaves it. So while a
    // request is waiting, Start is tapped for it. Counts frames since the
    // request, to pace the taps and to give up rather than press for ever.
    int stage_kick = -1;
    // A time attack run in progress. The game has no idea it is one: when the
    // run ends, however it ends, it sends the player to its own lobby. So the
    // frontend watches the zone and level, and when they are no longer the
    // ones it asked for the run is over -- and the level clock at that moment
    // is the time.
    time_attack::Run ta;
    // Every frame's pad is kept, so a session can be replayed exactly, headless,
    // and looked at afterwards. What the game does when a run is finished at
    // the goal is not something a script can reach, so the only way to study it
    // is to record somebody reaching it -- which means recording without their
    // having to arrange anything. A whole run is about 150 KB.
    // --record-input FILE writes it somewhere particular instead.
    std::string record_path;
    std::vector<uint32_t> recorded;      // pad 1 in the low word, pad 2 in the high
    // Every stage asked for, and when: the request is applied by a patch hook
    // rather than through the pad, so a replay has to be told about it.
    // Alongside the request, the settings that change how the game runs:
    // widescreen moves the camera clamp and what the engine streams, and a
    // 6-button pad is detected differently. A replay that does not match these
    // diverges partway through the level.
    struct StageEvent {
        uint64_t frame;
        stage_select::Request request;
        int wide = 0, wide_bottom = 0;
        bool six_button = false;
    };
    std::vector<StageEvent> recorded_stages;
    uint16_t prev_buttons = 0;
    // The menu is the front end: it owns the screen until the player chooses
    // START GAME, and the game owns it afterwards. Nothing about where the
    // game is has to be guessed from its memory.
    bool handed_over = false;
    // The title screen as it was when we handed over, so BACK TO TITLE can
    // return: the game itself offers no way back.
    std::unique_ptr<Machine> title_snapshot;
    // Touch devices have neither Esc nor a stick to click, so the progress
    // counter doubles as the way in. Empty when it is not being drawn.
    SDL_FRect achievement_tap{0, 0, 0, 0};
    struct Toast { std::string title, description; Uint64 until_ms = 0; };
    std::vector<Toast> toasts;
};

// Looks for a data file shipped with the build: next to the executable, in an
// "assets" folder beside it, or in the source tree during development.
std::string find_asset(const App& app, const std::string& name) {
    std::vector<std::filesystem::path> candidates;
    candidates.push_back(std::filesystem::path(app.store.root()) / name);
    if (const char* base = SDL_GetBasePath()) {
        candidates.push_back(std::filesystem::path(base) / name);
        candidates.push_back(std::filesystem::path(base) / "assets" / name);
        candidates.push_back(std::filesystem::path(base) / ".." / "assets" / name);
    }
    candidates.push_back(std::filesystem::path("assets") / name);
    for (const auto& c : candidates) {
        std::error_code ec;
        if (std::filesystem::exists(c, ec) && !ec) return c.string();
    }
    return "";
}

std::string achievements_progress_path(const App& app) {
    return app.store.save_dir() + "achievements.ini";
}

// One line of header, the stages that were asked for, then one pad word per
// emulated frame: enough for chaotix_headless --replay-input to play the
// session back exactly.
void write_recording(const App& app, const std::string& path, int result_frames = -1) {
    FILE* f = std::fopen(path.c_str(), "w");
    if (!f) { LOGW("app", "could not write %s", path.c_str()); return; }
    std::fprintf(f, "chaotix-input 1 frames=%zu\n", app.recorded.size());
    // What this session produced, so a replay can say at once whether it
    // reproduced the session or drifted off somewhere else.
    if (result_frames >= 0) std::fprintf(f, "result %d\n", result_frames);
    for (const auto& e : app.recorded_stages)
        std::fprintf(f, "stage %llu %u %u %u %u %u %d %d %d %d\n", (unsigned long long)e.frame,
                     e.request.place, e.request.level, e.request.attime, e.request.player,
                     e.request.combi, int(e.request.two_players), e.wide, e.wide_bottom,
                     int(e.six_button));
    for (uint32_t v : app.recorded) std::fprintf(f, "%X\n", v);
    std::fclose(f);
    LOGI("app", "session recorded to %s (%zu frames)", path.c_str(), app.recorded.size());
}

void capture_output(App& app) {
    SDL_Surface* s = SDL_RenderReadPixels(app.renderer, nullptr);
    if (!s) { LOGW("app", "SDL_RenderReadPixels: %s", SDL_GetError()); return; }
    SDL_Surface* c = SDL_ConvertSurface(s, SDL_PIXELFORMAT_XRGB8888);
    SDL_DestroySurface(s);
    if (!c) return;
    write_png(app.autotest_shot, static_cast<const uint32_t*>(c->pixels), c->w, c->h, c->pitch / 4);
    LOGI("app", "autotest: captured %dx%d output to %s", c->w, c->h, app.autotest_shot.c_str());
    SDL_DestroySurface(c);
}

// Places a user's ROM is likely to be, for the first-run setup to offer.
std::vector<std::string> rom_search_dirs(const App& app) {
    std::vector<std::filesystem::path> dirs = {"__ROM__", "rom", "."};
    if (const char* base = SDL_GetBasePath()) {
        dirs.push_back(std::filesystem::path(base) / "__ROM__");
        dirs.push_back(std::filesystem::path(base) / "rom");
        dirs.push_back(std::filesystem::path(base));
    }
    dirs.push_back(std::filesystem::path(app.store.root()) / "rom");
    // Desktop: the usual download/document folders. Mobile: the app's own
    // documents folder, which is what file managers expose.
    for (SDL_Folder f : {SDL_FOLDER_DOWNLOADS, SDL_FOLDER_DOCUMENTS, SDL_FOLDER_DESKTOP})
        if (const char* p = SDL_GetUserFolder(f)) {
            dirs.push_back(std::filesystem::path(p));
            dirs.push_back(std::filesystem::path(p) / "Chaotix");
        }
#if defined(SDL_PLATFORM_ANDROID)
    if (const char* ext = SDL_GetAndroidExternalStoragePath()) {
        dirs.push_back(std::filesystem::path(ext));
        dirs.push_back(std::filesystem::path(ext) / "rom");
    }
#endif
    std::vector<std::string> out;
    for (const auto& d : dirs) out.push_back(d.string());
    return out;
}

// Options that take a separate value, so a ROM path on the command line is
// not confused with one of them.
bool option_takes_value(const std::string& a) {
    static const char* with_value[] = {"--aspect", "--autotest", "--autotest-shot", "--window-size",
                                       "--press", "--user-dir", "--install", "--menu", "--keys", "--shots", "--hold", "--record-input"};
    for (const char* o : with_value)
        if (a == o) return true;
    return false;
}

// A ROM given on the command line wins over everything else.
std::string rom_from_args(int argc, char** argv) {
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (!a.empty() && a[0] == '-') {
            if (option_takes_value(a)) ++i;
            continue;
        }
        if (a.size() > 4) return a;
    }
    return "";
}

void apply_window_mode(App& app) {
    switch (app.cfg.window_mode) {
    case WindowMode::Windowed:
        SDL_SetWindowFullscreen(app.window, false);
        SDL_SetWindowBordered(app.window, true);
        break;
    case WindowMode::Borderless:
        SDL_SetWindowFullscreenMode(app.window, nullptr);  // desktop-sized, no mode change
        SDL_SetWindowFullscreen(app.window, true);
        break;
    case WindowMode::Fullscreen: {
        SDL_DisplayID disp = SDL_GetDisplayForWindow(app.window);
        const SDL_DisplayMode* dm = SDL_GetDesktopDisplayMode(disp);
        SDL_DisplayMode closest;
        if (dm && SDL_GetClosestFullscreenDisplayMode(disp, dm->w, dm->h, dm->refresh_rate, true, &closest))
            SDL_SetWindowFullscreenMode(app.window, &closest);
        SDL_SetWindowFullscreen(app.window, true);
        break;
    }
    }
}

uint16_t keyboard_buttons(const App& app, int player) {
    const bool* ks = SDL_GetKeyboardState(nullptr);
    const auto& binds = player == 0 ? app.cfg.keys : app.cfg.keys2;
    uint16_t out = 0;
    for (const auto& [name, keyname] : binds) {
        SDL_Scancode sc = SDL_GetScancodeFromName(keyname.c_str());
        if (sc != SDL_SCANCODE_UNKNOWN && ks[sc]) out |= pad_button_from_name(name.c_str());
    }
    return out;
}

// A binding that does not name a real key does nothing, silently, which is
// impossible to tell from a key that simply is not pressed. Say so once.
void warn_about_dead_bindings(const App& app) {
    for (int p = 0; p < 2; ++p) {
        for (const auto& [name, keyname] : (p == 0 ? app.cfg.keys : app.cfg.keys2)) {
            if (SDL_GetScancodeFromName(keyname.c_str()) == SDL_SCANCODE_UNKNOWN)
                LOGW("input", "player %d: \"%s\" is not a key name, so %s is unbound",
                     p + 1, keyname.c_str(), name.c_str());
        }
    }
}

// The Mega Drive pad the game sees, from whatever the player bound to it.
// Defaults are in Config::set_defaults; anything here can be rebound.
uint16_t gamepad_buttons(SDL_Gamepad* g, const std::map<std::string, std::string>& binds) {
    uint16_t out = 0;
    for (const auto& [name, sdl_name] : binds) {
        const SDL_GamepadButton b = SDL_GetGamepadButtonFromString(sdl_name.c_str());
        if (b != SDL_GAMEPAD_BUTTON_INVALID && SDL_GetGamepadButton(g, b))
            out |= pad_button_from_name(name.c_str());
    }
    // The sticks always steer, whatever the d-pad is bound to.
    const int dead = 12000;
    const int lx = SDL_GetGamepadAxis(g, SDL_GAMEPAD_AXIS_LEFTX);
    const int ly = SDL_GetGamepadAxis(g, SDL_GAMEPAD_AXIS_LEFTY);
    if (lx < -dead) out |= PAD_LEFT;
    if (lx > dead) out |= PAD_RIGHT;
    if (ly < -dead) out |= PAD_UP;
    if (ly > dead) out |= PAD_DOWN;
    return out;
}

// Which physical device drives a player: "auto", "keyboard", "padN", "none".
uint16_t device_buttons(const App& app, int player) {
    const std::string& dev = app.cfg.device[player];
    const std::string& other = app.cfg.device[1 - player];
    if (dev == "none") return 0;
    if (dev.rfind("pad", 0) == 0) {
        const size_t i = size_t(std::atoi(dev.c_str() + 3)) - 1;  // pad1 is the first
        const auto& binds = player == 0 ? app.cfg.pads : app.cfg.pads2;
        return i < app.pads.size() ? gamepad_buttons(app.pads[i], binds) : uint16_t(0);
    }
    uint16_t out = keyboard_buttons(app, player);
    // "auto" also answers to every gamepad, which is what someone who has
    // never opened the controls page expects. A pad the other player has
    // claimed is left alone, so the two do not drive each other.
    if (dev == "auto") {
        const auto& binds = player == 0 ? app.cfg.pads : app.cfg.pads2;
        for (size_t i = 0; i < app.pads.size(); ++i) {
            if (other == "pad" + std::to_string(i + 1)) continue;
            out |= gamepad_buttons(app.pads[i], binds);
        }
    }
    return out;
}

// Unlock notifications, newest at the bottom, and the full list on F7.
// The unlock counter (a way into the menu on a touch screen) and the
// notifications. The list itself is a page of the menu.
void draw_toasts(App& app) {
    ui::Ui& g = app.ui;
    if (!g.ready()) return;

    app.achievement_tap = {0, 0, 0, 0};
    if (app.touch_enabled && !app.menu.open()) {
        char label[32];
        std::snprintf(label, sizeof label, "%d/%zu", app.achievements.unlocked_count(),
                      app.achievements.list().size());
        const float w = g.text_width(ui::Font::Small, label) + g.px(22);
        const float h = g.line_height(ui::Font::Small) + g.px(12);
        const SDL_FRect r{g.width() - w - g.px(12), g.px(12), w, h};
        g.panel(r, ui::theme::surface.alpha(200), ui::theme::outline_strong, h * 0.5f);
        g.text(ui::Font::Small, r.x + g.px(11), r.y + g.px(6), label, ui::theme::text_dim);
        // The pill is small; the area that responds to a finger is padded out
        // around it so it clears the usual minimum touch target.
        const float pad = g.px(10);
        app.achievement_tap = {r.x - pad, r.y - pad, r.w + pad * 2, r.h + pad * 2};
    }

    const Uint64 now = SDL_GetTicks();
    app.toasts.erase(std::remove_if(app.toasts.begin(), app.toasts.end(),
                                    [&](const App::Toast& t) { return now >= t.until_ms; }),
                     app.toasts.end());
    const float toast_h = g.line_height(ui::Font::Body) + g.line_height(ui::Font::Small) + g.px(18);
    const float toast_w = std::min(g.width() - g.px(24), g.px(380));
    float ty = g.height() - g.px(14) - (toast_h + g.px(8)) * float(app.toasts.size());
    for (const auto& t : app.toasts) {
        const SDL_FRect box{g.px(14), ty, toast_w, toast_h};
        g.panel(box, ui::theme::surface_raised, ui::theme::accent, g.px(10), g.px(1.5f));
        g.text_fit(ui::Font::Small, box.x + g.px(14), ty + g.px(7), toast_w - g.px(28),
                   "ACHIEVEMENT UNLOCKED", ui::theme::accent);
        g.text_fit(ui::Font::Body, box.x + g.px(14), ty + g.px(6) + g.line_height(ui::Font::Small),
                   toast_w - g.px(28), t.title, ui::theme::text);
        ty += toast_h + g.px(8);
    }
}

void save_screenshot(App& app) {
    std::string dir = app.store.root() + "Screenshots/";
    std::error_code ec;
    std::filesystem::create_directories(dir, ec);
    char name[64];
    std::snprintf(name, sizeof name, "chaotix_%06llu.png", (unsigned long long)app.m->frame_count);
    write_png(dir + name, app.m->framebuffer, app.m->fb_width, app.m->fb_height, kScreenWidth);
    LOGI("app", "screenshot saved to %s%s", dir.c_str(), name);
}

// Every face and shoulder button is taken by the emulated 6-button pad (and
// Back is its Mode button), so the menu is on the left stick click, which
// nothing else uses. While the menu is open it drives the menu, not the game.
// Back to the title screen. The game has no way there itself, so the copy
// taken when we handed over is put back. That copy carries pointers into the
// machine it came from, so the buses are re-pointed afterwards.
bool return_to_title(App& app) {
    if (!app.title_snapshot) return false;
    *app.m = *app.title_snapshot;
    // The Start handed over at START GAME may still be in flight; leaving it
    // running would walk the game straight back out of the title.
    app.inject_start = 0;
    // A stage asked for but not yet started would fire on the way back in,
    // and its Start taps would go on pressing.
    app.m->stage_pending = false;
    app.stage_kick = -1;
    app.ta.cancel();
    app.m->remap_m68k();
    app.m->remap_sh2();
    app.handed_over = false;
    return true;
}

// Escape, and the pad button standing in for it. Before the game has been
// handed control this is the front end; afterwards it is the pause menu.
void menu_back(App& app) {
    if (app.menu.open()) { app.menu.close(); return; }
    if (app.handed_over) app.menu.toggle(); else app.menu.open_front();
}

// Escape's counterpart on a controller. Which button that is comes from the
// settings (CONTROLS -> MENU BUTTON); the left stick click stands in when the
// name there is not one SDL knows.
SDL_GamepadButton menu_pad_button(const App& app) {
    const SDL_GamepadButton b = SDL_GetGamepadButtonFromString(app.cfg.menu_button.c_str());
    return b == SDL_GAMEPAD_BUTTON_INVALID ? SDL_GAMEPAD_BUTTON_LEFT_STICK : b;
}

// A stage the front end asked for is taken at the game's mode dispatcher, and
// the title screen only gets back there once it is done with itself: one press
// of Start gets past its animation, another leaves it. So Start is tapped
// until the request is taken -- without this the stage waits out the whole
// title screen, about eight seconds of PUSH START.
uint16_t stage_kick_button(App& app) {
    if (app.stage_kick < 0) return 0;
    if (!app.m->stage_pending) {
        app.stage_kick = -1;   // taken: stop at once, or Start would pause the level
        return 0;
    }
    if (app.stage_kick > 900) {
        // Some scene the request cannot interrupt. Leave it waiting rather
        // than hold Start down on the game for ever.
        LOGW("stage", "the game has not come back to its mode dispatcher; the stage is still waiting");
        app.stage_kick = -1;
        return 0;
    }
    // Taps, not a hold: the title screen wants separate presses.
    const bool down = app.stage_kick % 24 < 6;
    ++app.stage_kick;
    return down ? uint16_t(PAD_START) : uint16_t(0);
}

// Watches a time attack run; called once per emulated frame. The game just
// moves the player on when a run ends, so the frontend takes the time and puts
// itself back instead, which is where the player came from.
void follow_time_attack(App& app) {
    if (!app.ta.update(*app.m)) return;
    const int frames = app.ta.time;
    const bool ran_out = app.ta.timed_out();
    const bool best = !ran_out && record_best(app.cfg, app.ta.request.place,
                                              app.ta.request.level, frames);
    // Straight to disk, the way an unlocked achievement is. Waiting for a
    // clean exit loses the record if the program does not get one.
    if (best) app.cfg.save(app.store.config_file());
    LOGI("stage", "time attack: over after %d frames%s", frames,
         ran_out ? " (the level's own limit)" : best ? " - a new best" : "");
    app.toasts.push_back({ran_out ? std::string("OUT OF TIME")
                                  : "TIME " + stage_select::format_time(frames),
                          ran_out ? "The level's own limit ran out."
                                  : (best ? "A new best for this stage." : "Not a new best."),
                          SDL_GetTicks() + 6000});
    // The run, as it was played. A recorded time that disagrees with what the
    // game showed can then be looked into without anyone having had to set up
    // a recording beforehand.
    write_recording(app, app.store.save_dir() + "last_run.txt", frames);
    if (return_to_title(app)) app.menu.show_page("timeattack");
}

void handle_pad_button(App& app, Uint8 button) {
    if (app.menu.on_pad(button)) return;
    if (SDL_GamepadButton(button) == menu_pad_button(app)) menu_back(app);
}

void handle_key(App& app, const SDL_KeyboardEvent& k) {
    if (k.repeat) return;
    // An open menu owns the keyboard, so the function keys below cannot be
    // triggered from underneath it.
    if (app.menu.on_key(k.key)) return;
    switch (k.key) {
    case SDLK_ESCAPE: menu_back(app); break;
    case SDLK_F1: app.cfg.debug_overlay = !app.cfg.debug_overlay; break;
    case SDLK_F2: {
        static const AspectMode order[] = {AspectMode::Auto, AspectMode::R4_3, AspectMode::R16_9, AspectMode::R16_10, AspectMode::R21_9};
        int i = 0;
        for (int j = 0; j < 5; ++j) if (order[j] == app.cfg.viewport.aspect) i = j;
        app.cfg.viewport.aspect = order[(i + 1) % 5];
        break;
    }
    case SDLK_F3:
        app.cfg.linear_filter = !app.cfg.linear_filter;
        SDL_SetTextureScaleMode(app.texture, app.cfg.linear_filter ? SDL_SCALEMODE_LINEAR : SDL_SCALEMODE_NEAREST);
        break;
    case SDLK_F4:
        app.cfg.viewport.scale = app.cfg.viewport.scale == ScaleMode::Fit ? ScaleMode::Integer
                               : app.cfg.viewport.scale == ScaleMode::Integer ? ScaleMode::Stretch : ScaleMode::Fit;
        break;
    case SDLK_F5: app.overlay_page = (app.overlay_page + 1) % 4; break;
    case SDLK_F6: app.cfg.widescreen = !app.cfg.widescreen; break;
    case SDLK_F7: app.menu.show_achievements(); break;
    case SDLK_F11:
        app.cfg.window_mode = app.cfg.window_mode == WindowMode::Windowed ? WindowMode::Borderless : WindowMode::Windowed;
        apply_window_mode(app);
        break;
    case SDLK_RETURN:
        if (k.mod & SDL_KMOD_ALT) {
            app.cfg.window_mode = app.cfg.window_mode == WindowMode::Windowed ? WindowMode::Borderless : WindowMode::Windowed;
            apply_window_mode(app);
        }
        break;
    case SDLK_F12: save_screenshot(app); break;
    default: break;
    }
}

void draw_touch_controls(App& app, uint16_t held) {
    SDL_SetRenderDrawBlendMode(app.renderer, SDL_BLENDMODE_BLEND);
    for (const auto& b : app.touch.buttons()) {
        bool on = b.is_dpad ? (held & (PAD_UP | PAD_DOWN | PAD_LEFT | PAD_RIGHT)) != 0 : (held & b.mask) != 0;
        SDL_SetRenderDrawColor(app.renderer, 255, 255, 255, on ? 110 : 55);
        // Approximate circles with a filled square plus cross for the d-pad.
        SDL_FRect r{b.cx - b.r * 0.7f, b.cy - b.r * 0.7f, b.r * 1.4f, b.r * 1.4f};
        if (b.is_dpad) {
            SDL_FRect h{b.cx - b.r, b.cy - b.r * 0.33f, b.r * 2, b.r * 0.66f};
            SDL_FRect v{b.cx - b.r * 0.33f, b.cy - b.r, b.r * 0.66f, b.r * 2};
            SDL_RenderFillRect(app.renderer, &h);
            SDL_RenderFillRect(app.renderer, &v);
        } else {
            SDL_RenderFillRect(app.renderer, &r);
            SDL_SetRenderDrawColor(app.renderer, 0, 0, 0, 200);
            SDL_RenderDebugText(app.renderer, b.cx - 4.0f * float(SDL_strlen(b.label)), b.cy - 4, b.label);
        }
    }
}

} // namespace

int main(int argc, char** argv) {
    App app;
    // The game image is 4:3 or wider: ask mobile platforms for landscape.
    SDL_SetHint(SDL_HINT_ORIENTATIONS, "LandscapeLeft LandscapeRight");
    if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMEPAD | SDL_INIT_AUDIO)) {
        std::fprintf(stderr, "SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }
    // --user-dir puts settings, saves and the installed ROM in a folder of the
    // caller's choice (portable installs, and the setup test).
    std::string user_dir;
    std::string install_path;  // --install: install this ROM and exit
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--user-dir" && i + 1 < argc) user_dir = argv[++i];
        else if (a == "--install" && i + 1 < argc) install_path = argv[++i];
    }
    if (!user_dir.empty() && user_dir.back() != '/' && user_dir.back() != '\\') user_dir += '/';
    if (user_dir.empty()) {
        char* pref = SDL_GetPrefPath("ChaotixRecompiled", "ChaotixRecompiled");
        user_dir = pref ? pref : "./";
        SDL_free(pref);
    } else {
        std::error_code ec;
        std::filesystem::create_directories(user_dir, ec);
    }
    app.store = SaveStore(user_dir);
    if (!app.cfg.load(app.store.config_file())) {
        app.cfg.set_defaults();
        app.cfg.save(app.store.config_file());
    }
    // Non-interactive install: verify and copy the ROM, then exit. Used by
    // packaging scripts and by the setup test.
    if (!install_path.empty()) {
        std::string installed, err;
        if (!setup::install(install_path, app.store.root(), &installed, &err)) {
            std::fprintf(stderr, "install failed: %s\n", err.c_str());
            SDL_Quit();
            return 1;
        }
        Rom rom;
        rom.load(installed, &err);
        app.cfg.installed = true;
        app.cfg.rom_sha1 = rom.sha1;
        app.cfg.rom_path = installed;
        app.cfg.save(app.store.config_file());
        std::printf("installed %s (%s)\n", installed.c_str(), rom.sha1.c_str());
        SDL_Quit();
        return 0;
    }

    bool force_interp = false;
    std::string menu_page;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--interp") force_interp = true;
        else if (a == "--fullscreen") app.cfg.window_mode = WindowMode::Fullscreen;
        else if (a == "--borderless") app.cfg.window_mode = WindowMode::Borderless;
        else if (a == "--windowed") app.cfg.window_mode = WindowMode::Windowed;
        else if (a == "--aspect" && i + 1 < argc) parse_aspect(argv[++i], app.cfg.viewport.aspect, app.cfg.viewport.custom_aspect);
        else if (a == "--no-widescreen") app.cfg.widescreen = false;
        else if (a == "--user-dir" && i + 1 < argc) ++i;  // handled above
        else if (a == "--touch") app.cfg.touch = TouchMode::On;
        else if (a == "--debug") app.cfg.debug_overlay = true;
        else if (a == "--autotest" && i + 1 < argc) app.autotest_frames = std::strtoull(argv[++i], nullptr, 10);
        else if (a == "--autotest-shot" && i + 1 < argc) app.autotest_shot = argv[++i];
        // Opens a menu page straight away, so it can be captured without a
        // keyboard (the same reason --autotest exists).
        else if (a == "--menu" && i + 1 < argc) menu_page = argv[++i];
        else if (a == "--keys" && i + 1 < argc) {
            // FRAME:KEYNAME[,FRAME:KEYNAME...]
            std::string spec = argv[++i];
            for (size_t st = 0; st < spec.size();) {
                size_t comma = spec.find(',', st);
                std::string one = spec.substr(st, comma == std::string::npos ? comma : comma - st);
                size_t colon = one.find(':');
                if (colon != std::string::npos) {
                    const SDL_Keycode k = SDL_GetKeyFromName(one.substr(colon + 1).c_str());
                    if (k == SDLK_UNKNOWN)
                        std::fprintf(stderr, "--keys: unknown key '%s'\n",
                                     one.substr(colon + 1).c_str());
                    else
                        app.key_script.push_back({std::strtoull(one.c_str(), nullptr, 10), k, false});
                }
                if (comma == std::string::npos) break;
                st = comma + 1;
            }
        }
        else if (a == "--shots" && i + 1 < argc) {
            // FRAME:FILE[,FRAME:FILE...]
            std::string spec = argv[++i];
            for (size_t st = 0; st < spec.size();) {
                size_t comma = spec.find(',', st);
                std::string one = spec.substr(st, comma == std::string::npos ? comma : comma - st);
                size_t colon = one.find(':');
                if (colon != std::string::npos)
                    app.extra_shots.push_back({std::strtoull(one.c_str(), nullptr, 10), one.substr(colon + 1), false});
                if (comma == std::string::npos) break;
                st = comma + 1;
            }
        }
        else if (a == "--record-input" && i + 1 < argc) app.record_path = argv[++i];
        else if (a == "--show-achievements") menu_page = "awards";
        else if (a == "--window-size" && i + 1 < argc) {
            int w = 0, h = 0;
            if (std::sscanf(argv[++i], "%dx%d", &w, &h) == 2) { app.cfg.raw["cli.w"] = std::to_string(w); app.cfg.raw["cli.h"] = std::to_string(h); }
        } else if ((a == "--press" || a == "--hold") && i + 1 < argc) {
            const bool host = a == "--hold";
            // FRAME:BUTTON[+BUTTON]:DURATION
            std::string spec = argv[++i];
            App::Press p{0, 4, 0};
            size_t c1 = spec.find(':'), c2 = spec.find(':', c1 + 1);
            p.frame = std::strtoull(spec.substr(0, c1).c_str(), nullptr, 10);
            std::string names = spec.substr(c1 + 1, c2 == std::string::npos ? std::string::npos : c2 - c1 - 1);
            if (c2 != std::string::npos) p.duration = std::strtoull(spec.substr(c2 + 1).c_str(), nullptr, 10);
            size_t st = 0;
            for (;;) {
                size_t plus = names.find('+', st);
                p.buttons |= pad_button_from_name(names.substr(st, plus == std::string::npos ? std::string::npos : plus - st).c_str());
                if (plus == std::string::npos) break;
                st = plus + 1;
            }
            if (host) app.host_script.push_back({p.frame, p.buttons, int(p.duration), false});
            else app.script.push_back(p);
        }
    }

    int win_h = kActiveLines * app.cfg.window_scale;
    int win_w = int(std::lround(win_h * 4.0 / 3.0));
    if (app.cfg.raw.count("cli.w")) { win_w = std::atoi(app.cfg.raw["cli.w"].c_str()); win_h = std::atoi(app.cfg.raw["cli.h"].c_str()); }
    app.window = SDL_CreateWindow("Knuckles' Chaotix Recompiled", win_w, win_h, SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY);
    if (!app.window) { std::fprintf(stderr, "SDL_CreateWindow: %s\n", SDL_GetError()); return 1; }
    app.renderer = SDL_CreateRenderer(app.window, nullptr);
    if (!app.renderer) { std::fprintf(stderr, "SDL_CreateRenderer: %s\n", SDL_GetError()); return 1; }
    SDL_SetRenderVSync(app.renderer, app.cfg.vsync ? 1 : 0);
    LOGI("app", "renderer: %s", SDL_GetRendererName(app.renderer));
    if (!app.ui.init(app.renderer)) LOGW("app", "no UI font; the menu is unavailable");
    app.menu.bind(app.cfg);
    {
        // Set field by field: a positional list silently shifts every hook
        // along when one is added in the middle.
        Menu::Hooks hooks;
        hooks.apply_video = [&app] {
            SDL_SetRenderVSync(app.renderer, app.cfg.vsync ? 1 : 0);
            if (app.texture)
                SDL_SetTextureScaleMode(app.texture, app.cfg.linear_filter ? SDL_SCALEMODE_LINEAR
                                                                           : SDL_SCALEMODE_NEAREST);
            apply_window_mode(app);
        };
        hooks.quit = [&app] { app.running = false; };
        hooks.start_game = [&app] {
            // Keep the title screen so BACK TO TITLE can return to it, then
            // give the game the Start it is waiting for: it proceeds into its
            // own menus exactly as it would have without us in the way.
            if (!app.title_snapshot) app.title_snapshot = std::make_unique<Machine>();
            *app.title_snapshot = *app.m;
            app.handed_over = true;
            app.inject_start = 8;
        };
        hooks.start_stage = [&app](const stage_select::Request& r) {
            // Same hand-over as START GAME, but from the title screen rather
            // than wherever the game happens to be: the request is applied at
            // the game's mode dispatcher, which a running level never reaches.
            if (app.handed_over) return_to_title(app);
            if (!app.title_snapshot) app.title_snapshot = std::make_unique<Machine>();
            *app.title_snapshot = *app.m;
            app.m->stage_request = r;
            app.m->stage_pending = true;
            app.handed_over = true;
            // Tapping Start until the request is taken, rather than one press:
            // a single one only gets the title past its own animation, and the
            // stage would then wait out the whole title screen (about eight
            // seconds of PUSH START) before the game came back to the
            // dispatcher on its own.
            app.inject_start = 0;
            app.stage_kick = 0;
            app.ta.begin(r);
            app.recorded_stages.push_back({app.m->frame_count, r, app.m->wide_extra,
                                           app.m->wide_extra_bottom, app.cfg.six_button});
        };
        hooks.back_to_title = [&app] {
            if (return_to_title(app)) app.menu.open_front();
        };
        hooks.pad_count = [&app] { return int(app.pads.size()); };
        hooks.pad_name = [&app](int i) -> std::string {
            if (i < 0 || size_t(i) >= app.pads.size()) return "";
            const char* n = SDL_GetGamepadName(app.pads[size_t(i)]);
            return n ? n : "";
        };
        hooks.reset_awards = [&app] {
            app.achievements.reset_progress();
            std::error_code ec;
            std::filesystem::remove(achievements_progress_path(app), ec);
        };
        app.menu.set_hooks(std::move(hooks));
    }
    // The menu is the front end, so it is up from the start: the game boots
    // behind it and its title screen and attract demo are the backdrop.
    app.menu.open_front();
    if (!menu_page.empty() && !app.menu.show_page(menu_page))
        LOGW("app", "--menu: unknown page '%s' (front, main, options, controls, awards)",
             menu_page.c_str());

    // Where to get the ROM, in order: the command line, the copy installed
    // by a previous run, then the config or the usual folders.
    std::string rom_path = rom_from_args(argc, argv);
    if (rom_path.empty() && app.cfg.installed && setup::is_installed(app.store.root(), app.cfg.rom_sha1))
        rom_path = setup::installed_rom_path(app.store.root());
    if (rom_path.empty() && !app.cfg.rom_path.empty() && std::filesystem::exists(app.cfg.rom_path))
        rom_path = app.cfg.rom_path;

    app.m = std::make_unique<Machine>();
    std::string err;
    if (rom_path.empty() || !app.m->load_rom(rom_path, &err)) {
        if (app.autotest_frames) {  // tests never show the setup screen
            std::fprintf(stderr, "no usable ROM: %s\n", err.c_str());
            return 1;
        }
        // First run, or the ROM moved: let the user install one.
        rom_path = run_setup_screen(app.window, app.renderer, app.store.root(), rom_search_dirs(app));
        if (rom_path.empty()) { SDL_Quit(); return 0; }
        app.m = std::make_unique<Machine>();
        if (!app.m->load_rom(rom_path, &err)) {
            SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Knuckles' Chaotix Recompiled", err.c_str(), app.window);
            SDL_Quit();
            return 1;
        }
    }
    // Remember the installed copy so the next launch starts straight up.
    if (rom_path == setup::installed_rom_path(app.store.root())) {
        app.cfg.installed = true;
        app.cfg.rom_sha1 = app.m->rom.sha1;
        app.cfg.rom_path = rom_path;
        app.cfg.save(app.store.config_file());
    }
    if (app.m->rom.version == RomVersion::Unknown)
        SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_WARNING, "Knuckles' Chaotix Recompiled",
                                 "This ROM does not match the verified Knuckles' Chaotix (Japan, USA) image.\n"
                                 "The recompiled code will not be used; the reference interpreter will run it instead.",
                                 app.window);
    app.m->input.six_button[0] = app.cfg.six_button;
    app.m->input.six_button[1] = app.cfg.six_button;
    warn_about_dead_bindings(app);
    app.m->reset();
    if (!app.autotest_frames) app.store.load_sram(*app.m);  // autotests are hermetic
    RecompStatus rs = install_recompiled_code(*app.m, app.cfg.use_recompiled && !force_interp);
    LOGI("app", "execution: %s", rs.description.c_str());

    if (app.cfg.achievements) {
        // A file in the user data directory (or beside the executable) wins,
        // so definitions can be edited without rebuilding; otherwise the
        // copy compiled into the binary is used.
        const std::string defs = find_asset(app, "achievements.ini");
        std::string aerr;
        const bool loaded =
            defs.empty()
                ? app.achievements.load_definitions_text(
                      std::string(reinterpret_cast<const char*>(achievements_ini),
                                  achievements_ini_len),
                      &aerr)
                : app.achievements.load_definitions(defs, &aerr);
        if (!loaded) {
            LOGW("achievements", "%s", aerr.c_str());
        } else {
            std::error_code ec;
            std::filesystem::create_directories(app.store.save_dir(), ec);
            app.achievements.load_progress(achievements_progress_path(app));
            app.achievements_on = true;
            LOGI("achievements", "%zu definitions, %d/%d points already earned",
                 app.achievements.list().size(), app.achievements.points_earned(), app.achievements.points_total());
        }
    }
    app.texture = SDL_CreateTexture(app.renderer, SDL_PIXELFORMAT_XRGB8888, SDL_TEXTUREACCESS_STREAMING, kScreenWidth, kScreenHeight);
    SDL_SetTextureScaleMode(app.texture, app.cfg.linear_filter ? SDL_SCALEMODE_LINEAR : SDL_SCALEMODE_NEAREST);
    apply_window_mode(app);
    if (app.cfg.audio && !app.autotest_frames) {
        // The machine produces 16-bit stereo at the YM2612 native rate; SDL
        // resamples to the device. Emulated time drives production, so the
        // audio device never changes game speed.
        SDL_AudioSpec spec{SDL_AUDIO_S16, 2, int(kAudioRate + 0.5)};
        app.audio = SDL_OpenAudioDeviceStream(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, &spec, nullptr, nullptr);
        if (app.audio) {
            SDL_SetAudioStreamGain(app.audio, float(app.cfg.volume) / 100.0f);
            SDL_ResumeAudioStreamDevice(app.audio);
            app.m->audio_enabled = true;
        } else {
            LOGW("audio", "cannot open audio device: %s", SDL_GetError());
        }
    }
    // On: always drawn. Auto: only once the screen has actually been touched,
    // so a phone plugged into a controller is not covered in buttons nobody
    // is using. Off: never.
    app.touch_enabled = app.cfg.touch == TouchMode::On;

    const uint64_t freq = SDL_GetPerformanceFrequency();
    const double frame_ticks = double(freq) / kNtscFrameRate;
    uint64_t last = SDL_GetPerformanceCounter();
    double accumulator = 0;
    uint64_t fps_t0 = last, fps_frames = 0, fps_sims = 0;

    while (app.running) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            switch (e.type) {
            case SDL_EVENT_QUIT: app.running = false; break;
            case SDL_EVENT_KEY_DOWN: handle_key(app, e.key); break;
            case SDL_EVENT_GAMEPAD_BUTTON_DOWN: handle_pad_button(app, e.gbutton.button); break;
            case SDL_EVENT_GAMEPAD_ADDED:
                if (SDL_Gamepad* g = SDL_OpenGamepad(e.gdevice.which)) {
                    app.pads.push_back(g);
                    LOGI("input", "gamepad connected: %s", SDL_GetGamepadName(g));
                }
                break;
            case SDL_EVENT_GAMEPAD_REMOVED:
                for (size_t i = 0; i < app.pads.size(); ++i)
                    if (SDL_GetGamepadID(app.pads[i]) == e.gdevice.which) { SDL_CloseGamepad(app.pads[i]); app.pads.erase(app.pads.begin() + long(i)); break; }
                break;
            case SDL_EVENT_FINGER_DOWN: case SDL_EVENT_FINGER_MOTION: {
                app.touch_enabled = app.cfg.touch != TouchMode::Off;
                int w = 0, h = 0;
                SDL_GetRenderOutputSize(app.renderer, &w, &h);
                const float tx = e.tfinger.x * float(w), ty = e.tfinger.y * float(h);
                if (app.menu.open()) {
                    if (e.type == SDL_EVENT_FINGER_DOWN) app.menu.on_touch_down(tx, ty);
                    break;
                }
                if (e.type == SDL_EVENT_FINGER_DOWN && app.achievements_on) {
                    const SDL_FRect& r = app.achievement_tap;
                    if (r.w > 0 && tx >= r.x && tx <= r.x + r.w && ty >= r.y && ty <= r.y + r.h) {
                        app.menu.show_achievements();
                        break;
                    }
                }
                app.fingers[e.tfinger.fingerID] = app.touch.hit(tx, ty);
                break;
            }
            case SDL_EVENT_FINGER_UP: case SDL_EVENT_FINGER_CANCELED:
                if (app.menu.open()) { app.menu.on_touch_up(); break; }
                app.fingers.erase(e.tfinger.fingerID);
                break;
            case SDL_EVENT_WINDOW_FOCUS_LOST: case SDL_EVENT_DID_ENTER_BACKGROUND:
                if (app.m->sram_dirty) app.store.store_sram(*app.m);
                break;
            default: break;
            }
        }
        const bool* ks = SDL_GetKeyboardState(nullptr);
        app.fast_forward = ks[SDL_SCANCODE_TAB];

        // Unified input: keyboard | gamepads | touch -> InputState. While the
        // menu is open it takes the controls, so driving it does not also move
        // the character.
        uint16_t touch_held = 0;
        for (const auto& [id, b] : app.fingers) touch_held |= b;
        uint16_t raw = 0, raw2 = 0;
        // Emulated frames advance in batches, so a window of frame numbers can
        // be stepped straight over: arm on reaching the frame, then hold for a
        // number of passes round this loop.
        for (auto& h : app.host_script) {
            if (!h.armed && app.m->frame_count >= h.frame) { h.armed = true; h.remaining = int(h.frame ? h.remaining : h.remaining); }
            if (h.armed && h.remaining > 0) { raw |= h.buttons; --h.remaining; }
        }
        if (!app.menu.open()) {
            // Touch belongs to player 1; the on-screen pad has no second set.
            raw |= device_buttons(app, 0) | touch_held;
            raw2 = device_buttons(app, 1);
        }
        uint16_t buttons = raw;
        app.prev_buttons = raw;
        if (app.inject_start > 0) { buttons |= PAD_START; --app.inject_start; }
        app.m->input.pad[0] = buttons;
        app.m->input.pad[1] = raw2;

        // Fixed-timestep simulation at the original frame rate, independent of
        // the display refresh rate (120/144 Hz monitors do not speed up the game).
        uint64_t now = SDL_GetPerformanceCounter();
        accumulator += double(now - last);
        last = now;
        if (accumulator > frame_ticks * 8) accumulator = frame_ticks * 8;  // after a stall, don't spiral
        {
            // True widescreen margins follow the display aspect (levels only;
            // see runtime/patches.h). Takes effect at the next level load.
            int ww = 0, wh = 0;
            SDL_GetRenderOutputSize(app.renderer, &ww, &wh);
            const double fa = aspect_value(app.cfg.viewport.aspect, app.cfg.viewport.custom_aspect, wh > 0 ? double(ww) / double(wh) : 0.0);
            app.m->wide_extra = app.cfg.widescreen ? widescreen_extra(fa, patches::kMaxWideExtra) : 0;
            // A frame taller than 4:3 gets extra rows below instead.
            app.m->wide_extra_bottom = app.cfg.widescreen ? widescreen_rows(fa, patches::kMaxWideExtraBottom) : 0;
        }
        int steps = 0;
        const int max_steps = app.fast_forward ? 8 : 3;
        uint64_t emu_t0 = SDL_GetPerformanceCounter();
        const bool autotest = app.autotest_frames != 0;
        // With scripted host input the loop runs one emulated frame per pass,
        // so a "hold for N frames" means N frames rather than N batches of up
        // to 64 - the difference between a tap and holding the button down.
        const int autotest_batch = app.host_script.empty() ? 64 : 1;
        while ((accumulator >= frame_ticks || app.fast_forward || autotest) &&
               steps < (autotest ? autotest_batch : max_steps)) {
            if (autotest && app.m->frame_count >= app.autotest_frames) break;
            // Scripted keys are pushed as events and handled on the next pass
            // round the event loop, exactly like a key someone pressed.
            for (auto& k : app.key_script) {
                if (k.done || app.m->frame_count < k.frame) continue;
                k.done = true;
                SDL_Event ke{};
                ke.type = SDL_EVENT_KEY_DOWN;
                ke.key.key = k.key;
                ke.key.down = true;
                ke.key.repeat = false;
                SDL_PushEvent(&ke);
            }
            // Scripted input is applied per emulated frame (deterministic).
            uint16_t scripted = 0;
            for (const auto& p : app.script)
                if (app.m->frame_count >= p.frame && app.m->frame_count < p.frame + p.duration) scripted |= p.buttons;
            // And so are the taps of Start that carry a waiting stage request
            // through the title screen: counted in emulated frames, or a pass
            // that simulates several would stretch a tap into a hold.
            scripted |= stage_kick_button(app);
            app.m->input.pad[0] = uint16_t(buttons | scripted);
            app.recorded.push_back(uint32_t(uint16_t(buttons | scripted)) | uint32_t(raw2) << 16);
            app.m->input.pad[1] = raw2;
            app.m->run_frame();
            follow_time_attack(app);
            if (app.achievements_on) {
                app.achievements.update(*app.m, [&](const achievements::Achievement& a) {
                    app.toasts.push_back({a.title, a.description, SDL_GetTicks() + 5000});
                    app.achievements.save_progress(achievements_progress_path(app));
                });
            }
            if (!app.fast_forward) accumulator -= frame_ticks;
            ++steps;
        }
        if (app.fast_forward) accumulator = 0;
        uint64_t emu_t1 = SDL_GetPerformanceCounter();
        if (steps) app.timing.emu_ms = double(emu_t1 - emu_t0) * 1000.0 / double(freq) / steps;
        fps_sims += uint64_t(steps);

        // Audio: hand over what the machine produced; keep ~50 ms queued with a
        // gentle rate adjustment instead of dropping or stretching audio.
        if (app.audio) {
            if (!app.m->audio_out.empty()) {
                if (app.fast_forward) app.m->audio_out.clear();
                else {
                    SDL_PutAudioStreamData(app.audio, app.m->audio_out.data(), int(app.m->audio_out.size() * sizeof(int16_t)));
                    app.m->audio_out.clear();
                }
            }
            const double target = kAudioRate * 0.05 * 4;  // bytes queued for 50 ms (stereo s16)
            double queued = double(SDL_GetAudioStreamQueued(app.audio));
            double err = (queued - target) / target;
            float ratio = float(1.0 + std::clamp(err * 0.01, -0.01, 0.01));
            SDL_SetAudioStreamFrequencyRatio(app.audio, ratio);
            if (queued > target * 6) SDL_ClearAudioStream(app.audio);  // after a stall
        } else {
            app.m->audio_out.clear();
        }

        // SRAM autosave shortly after the game writes it.
        if (app.m->sram_dirty && !app.autotest_frames) {
            if (!app.sram_dirty_since) app.sram_dirty_since = now;
            else if (double(now - app.sram_dirty_since) / double(freq) > 1.0) { app.store.store_sram(*app.m); app.sram_dirty_since = 0; }
        }

        // Present
        uint64_t pr_t0 = SDL_GetPerformanceCounter();
        int ow = 0, oh = 0;
        SDL_GetRenderOutputSize(app.renderer, &ow, &oh);
        SDL_SetRenderDrawColor(app.renderer, 0, 0, 0, 255);
        SDL_RenderClear(app.renderer);
        SDL_UpdateTexture(app.texture, nullptr, app.m->framebuffer, kScreenWidth * 4);
        app.cfg.viewport.image_aspect = image_aspect_for_size(app.m->fb_width, app.m->fb_width - 2 * app.m->fb_extra,
                                                              app.m->fb_height, app.m->fb_height - app.m->fb_extra_bottom);
        ViewportResult vp = compute_viewport(app.cfg.viewport, ow, oh, app.m->fb_width, app.m->fb_height);
        SDL_FRect src{0, 0, float(app.m->fb_width), float(app.m->fb_height)};
        SDL_FRect dst{float(vp.image.x), float(vp.image.y), float(vp.image.w), float(vp.image.h)};
        // The front end puts the game's own picture beside its list instead of
        // behind it, and says where.
        SDL_FRect art{};
        bool panelled = false;
        if (app.ui.ready()) {
            app.ui.begin_frame();
            panelled = app.menu.art_panel(app.ui, &art);
        }
        // With a panel the picture is drawn twice: once filling the window as
        // a backdrop, which the menu then dims, and once in the panel itself.
        SDL_RenderTexture(app.renderer, app.texture, &src, &dst);
        if (panelled) {
            app.menu.draw_backdrop_dim(app.ui);
            SDL_RenderTexture(app.renderer, app.texture, &src, &art);
        }
        if (app.touch_enabled) {
            app.touch.layout(ow, oh);
            draw_touch_controls(app, touch_held);
        }
        if (app.ui.ready()) {
            app.menu.draw(app.ui, app.achievements);
            if (app.achievements_on) draw_toasts(app);
            app.ui.end_frame();
        }
        if (app.cfg.debug_overlay) {
            const SDL_DisplayMode* dm = SDL_GetCurrentDisplayMode(SDL_GetDisplayForWindow(app.window));
            app.timing.refresh_hz = dm ? unsigned(dm->refresh_rate + 0.5f) : 0;
            app.timing.fast_forward = app.fast_forward;
            char vline[200];
            std::snprintf(vline, sizeof vline, "video: %dx%d out, image %.0fx%.0f, aspect %s, %s, %s, %s, wide %d+%d%s", ow, oh, vp.image.w, vp.image.h,
                          aspect_name(app.cfg.viewport.aspect), scale_name(app.cfg.viewport.scale),
                          app.cfg.linear_filter ? "linear" : "nearest", window_mode_name(app.cfg.window_mode),
                          app.m->fb_extra, app.m->fb_extra_bottom, app.m->wide_active ? " (active)" : "");
            auto lines = build_debug_overlay(*app.m, app.timing, app.overlay_page, vline, app.watches);
            float scale = std::max(1.0f, float(oh) / 540.0f);
            SDL_SetRenderScale(app.renderer, scale, scale);
            SDL_SetRenderDrawBlendMode(app.renderer, SDL_BLENDMODE_BLEND);
            SDL_SetRenderDrawColor(app.renderer, 0, 0, 0, 170);
            SDL_FRect bg{0, 0, 8.0f * 100, 10.0f * float(lines.size()) + 4};
            SDL_RenderFillRect(app.renderer, &bg);
            SDL_SetRenderDrawColor(app.renderer, 255, 255, 160, 255);
            for (size_t i = 0; i < lines.size(); ++i) SDL_RenderDebugText(app.renderer, 4, 4 + 10.0f * float(i), lines[i].c_str());
            SDL_SetRenderScale(app.renderer, 1, 1);
        }
        if (app.autotest_frames && app.m->frame_count >= app.autotest_frames) {
            if (!app.autotest_shot.empty()) capture_output(app);
            app.running = false;
        }
        // Emulated frames advance in batches, so fire on "reached" rather
        // than "equals" or the moment is stepped straight over.
        for (auto& shot : app.extra_shots) {
            if (shot.done || app.m->frame_count < shot.frame) continue;
            shot.done = true;
            const std::string keep = app.autotest_shot;
            app.autotest_shot = shot.path;
            capture_output(app);
            app.autotest_shot = keep;
        }
        SDL_RenderPresent(app.renderer);
        app.timing.present_ms = double(SDL_GetPerformanceCounter() - pr_t0) * 1000.0 / double(freq);
        ++fps_frames;
        if (now - fps_t0 > freq) {
            double s = double(now - fps_t0) / double(freq);
            app.timing.render_fps = double(fps_frames) / s;
            app.timing.sim_fps = double(fps_sims) / s;
            fps_frames = fps_sims = 0;
            fps_t0 = now;
        }
        if (!app.cfg.vsync && steps == 0) SDL_Delay(1);
    }

    if (!app.autotest_frames) {
        if (app.m->sram_dirty) app.store.store_sram(*app.m);
        app.cfg.save(app.store.config_file());
    }
    if (!app.record_path.empty()) write_recording(app, app.record_path);
    if (app.audio) SDL_DestroyAudioStream(app.audio);
    for (SDL_Gamepad* g : app.pads) SDL_CloseGamepad(g);
    SDL_DestroyTexture(app.texture);
    SDL_DestroyRenderer(app.renderer);
    SDL_DestroyWindow(app.window);
    SDL_Quit();
    return 0;
}
